create table if not exists migration_jobs (
    id uuid primary key,
    source_playlist_url varchar(2048) not null,
    target_platform varchar(64) not null,
    status varchar(32) not null,
    total_tracks integer not null default 0,
    matched_tracks integer not null default 0,
    failed_tracks integer not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists migration_tracks (
    id bigint generated by default as identity primary key,
    job_id uuid not null,
    source_track_name varchar(512) not null,
    source_artist_name varchar(512) not null,
    source_album_name varchar(512),
    target_track_id varchar(512),
    target_track_url varchar(2048),
    target_track_title varchar(1024),
    target_thumbnail_url varchar(2048),
    youtube_video_id varchar(512),
    youtube_title varchar(1024),
    match_status varchar(32) not null,
    match_score double precision,
    confidence_score double precision,
    failure_reason varchar(2048),
    created_at timestamp with time zone not null,
    constraint fk_migration_tracks_job foreign key (job_id) references migration_jobs(id) on delete cascade
);

alter table migration_tracks add column if not exists target_track_title varchar(1024);
alter table migration_tracks add column if not exists target_thumbnail_url varchar(2048);
alter table migration_tracks add column if not exists youtube_video_id varchar(512);
alter table migration_tracks add column if not exists youtube_title varchar(1024);
alter table migration_tracks add column if not exists match_score double precision;

create index if not exists idx_migration_tracks_job_id on migration_tracks(job_id);
