create table if not exists migration_jobs (
    id uuid primary key,
    source_playlist_url varchar(2048) not null,
    spotify_access_token varchar(4096),
    google_access_token varchar(4096),
    target_platform varchar(64) not null,
    target_playlist_id varchar(512),
    target_playlist_url varchar(2048),
    status varchar(32) not null,
    total_tracks integer not null default 0,
    matched_tracks integer not null default 0,
    failed_tracks integer not null default 0,
    last_processed_index integer not null default 0,
    paused_reason varchar(1024),
    quota_units_estimated integer,
    next_retry_time timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists track_match_cache (
    id bigint generated by default as identity primary key,
    user_id uuid,
    track_title varchar(512) not null,
    artist varchar(512) not null,
    normalized_track_title varchar(512) not null,
    normalized_artist varchar(512) not null,
    youtube_video_id varchar(512) not null,
    created_at timestamp with time zone not null
);

create table if not exists migration_tracks (
    id bigint generated by default as identity primary key,
    job_id uuid not null,
    source_track_name varchar(512) not null,
    source_artist_name varchar(512) not null,
    source_album_name varchar(512),
    target_track_id varchar(512),
    target_track_url varchar(2048),
    target_track_title varchar(1024),
    target_thumbnail_url varchar(2048),
    youtube_video_id varchar(512),
    youtube_title varchar(1024),
    match_status varchar(32) not null,
    match_score double precision,
    confidence_score double precision,
    failure_reason varchar(2048),
    created_at timestamp with time zone not null,
    constraint fk_migration_tracks_job foreign key (job_id) references migration_jobs(id) on delete cascade
);

alter table migration_tracks add column if not exists target_track_title varchar(1024);
alter table migration_tracks add column if not exists target_thumbnail_url varchar(2048);
alter table migration_tracks add column if not exists youtube_video_id varchar(512);
alter table migration_tracks add column if not exists youtube_title varchar(1024);
alter table migration_tracks add column if not exists match_score double precision;
alter table migration_jobs add column if not exists spotify_access_token varchar(4096);
alter table migration_jobs add column if not exists google_access_token varchar(4096);
alter table migration_jobs add column if not exists target_playlist_id varchar(512);
alter table migration_jobs add column if not exists target_playlist_url varchar(2048);
alter table migration_jobs add column if not exists last_processed_index integer not null default 0;
alter table migration_jobs add column if not exists paused_reason varchar(1024);
alter table migration_jobs add column if not exists quota_units_estimated integer;
alter table migration_jobs add column if not exists next_retry_time timestamp with time zone;

create index if not exists idx_migration_tracks_job_id on migration_tracks(job_id);
create index if not exists idx_track_match_cache_lookup
    on track_match_cache(user_id, normalized_track_title, normalized_artist);

-- User Management Tables (for Supabase Auth integration)
create table if not exists users (
    id uuid primary key,
    email varchar(255) unique not null,
    display_name varchar(255),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Add user_id to migration_jobs for multi-user support
alter table migration_jobs add column if not exists user_id uuid;
alter table migration_jobs add constraint fk_migration_jobs_user foreign key (user_id) references users(id) on delete cascade;

create index if not exists idx_migration_jobs_user_id on migration_jobs(user_id);
create index if not exists idx_users_email on users(email);
